//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TIEMBANH.KhachHang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KhachHang.IKhachHang")]
    public interface IKhachHang {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/InsertKhachHang", ReplyAction="http://tempuri.org/IKhachHang/InsertKhachHangResponse")]
        void InsertKhachHang(string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/InsertKhachHang", ReplyAction="http://tempuri.org/IKhachHang/InsertKhachHangResponse")]
        System.Threading.Tasks.Task InsertKhachHangAsync(string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/showGV", ReplyAction="http://tempuri.org/IKhachHang/showGVResponse")]
        System.Data.DataTable showGV();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/showGV", ReplyAction="http://tempuri.org/IKhachHang/showGVResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showGVAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/UpdateKhachHang", ReplyAction="http://tempuri.org/IKhachHang/UpdateKhachHangResponse")]
        void UpdateKhachHang(int makh, string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/UpdateKhachHang", ReplyAction="http://tempuri.org/IKhachHang/UpdateKhachHangResponse")]
        System.Threading.Tasks.Task UpdateKhachHangAsync(int makh, string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/DelKhachHang", ReplyAction="http://tempuri.org/IKhachHang/DelKhachHangResponse")]
        void DelKhachHang(int makh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/DelKhachHang", ReplyAction="http://tempuri.org/IKhachHang/DelKhachHangResponse")]
        System.Threading.Tasks.Task DelKhachHangAsync(int makh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/SearchKhachHang", ReplyAction="http://tempuri.org/IKhachHang/SearchKhachHangResponse")]
        System.Data.DataTable SearchKhachHang(string tenkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKhachHang/SearchKhachHang", ReplyAction="http://tempuri.org/IKhachHang/SearchKhachHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchKhachHangAsync(string tenkh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKhachHangChannel : QL_TIEMBANH.KhachHang.IKhachHang, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KhachHangClient : System.ServiceModel.ClientBase<QL_TIEMBANH.KhachHang.IKhachHang>, QL_TIEMBANH.KhachHang.IKhachHang {
        
        public KhachHangClient() {
        }
        
        public KhachHangClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KhachHangClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KhachHangClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KhachHangClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertKhachHang(string tenkh, string diachi, string dienthoai) {
            base.Channel.InsertKhachHang(tenkh, diachi, dienthoai);
        }
        
        public System.Threading.Tasks.Task InsertKhachHangAsync(string tenkh, string diachi, string dienthoai) {
            return base.Channel.InsertKhachHangAsync(tenkh, diachi, dienthoai);
        }
        
        public System.Data.DataTable showGV() {
            return base.Channel.showGV();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showGVAsync() {
            return base.Channel.showGVAsync();
        }
        
        public void UpdateKhachHang(int makh, string tenkh, string diachi, string dienthoai) {
            base.Channel.UpdateKhachHang(makh, tenkh, diachi, dienthoai);
        }
        
        public System.Threading.Tasks.Task UpdateKhachHangAsync(int makh, string tenkh, string diachi, string dienthoai) {
            return base.Channel.UpdateKhachHangAsync(makh, tenkh, diachi, dienthoai);
        }
        
        public void DelKhachHang(int makh) {
            base.Channel.DelKhachHang(makh);
        }
        
        public System.Threading.Tasks.Task DelKhachHangAsync(int makh) {
            return base.Channel.DelKhachHangAsync(makh);
        }
        
        public System.Data.DataTable SearchKhachHang(string tenkh) {
            return base.Channel.SearchKhachHang(tenkh);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchKhachHangAsync(string tenkh) {
            return base.Channel.SearchKhachHangAsync(tenkh);
        }
    }
}
