//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_TIEMBANH.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IServices")]
    public interface IServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertSanPham", ReplyAction="http://tempuri.org/IServices/InsertSanPhamResponse")]
        void InsertSanPham(string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertSanPham", ReplyAction="http://tempuri.org/IServices/InsertSanPhamResponse")]
        System.Threading.Tasks.Task InsertSanPhamAsync(string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVSanPham", ReplyAction="http://tempuri.org/IServices/showGVSanPhamResponse")]
        System.Data.DataTable showGVSanPham();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVSanPham", ReplyAction="http://tempuri.org/IServices/showGVSanPhamResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showGVSanPhamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateSanPham", ReplyAction="http://tempuri.org/IServices/UpdateSanPhamResponse")]
        void UpdateSanPham(int masp, string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateSanPham", ReplyAction="http://tempuri.org/IServices/UpdateSanPhamResponse")]
        System.Threading.Tasks.Task UpdateSanPhamAsync(int masp, string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelSanPham", ReplyAction="http://tempuri.org/IServices/DelSanPhamResponse")]
        void DelSanPham(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelSanPham", ReplyAction="http://tempuri.org/IServices/DelSanPhamResponse")]
        System.Threading.Tasks.Task DelSanPhamAsync(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SearchSanPham", ReplyAction="http://tempuri.org/IServices/SearchSanPhamResponse")]
        System.Data.DataTable SearchSanPham(string tensp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SearchSanPham", ReplyAction="http://tempuri.org/IServices/SearchSanPhamResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchSanPhamAsync(string tensp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showComboxSanPham", ReplyAction="http://tempuri.org/IServices/showComboxSanPhamResponse")]
        System.Data.DataTable showComboxSanPham();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showComboxSanPham", ReplyAction="http://tempuri.org/IServices/showComboxSanPhamResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showComboxSanPhamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertNhanVien", ReplyAction="http://tempuri.org/IServices/InsertNhanVienResponse")]
        void InsertNhanVien(string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertNhanVien", ReplyAction="http://tempuri.org/IServices/InsertNhanVienResponse")]
        System.Threading.Tasks.Task InsertNhanVienAsync(string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVNhanVien", ReplyAction="http://tempuri.org/IServices/showGVNhanVienResponse")]
        System.Data.DataTable showGVNhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVNhanVien", ReplyAction="http://tempuri.org/IServices/showGVNhanVienResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showGVNhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateNhanVien", ReplyAction="http://tempuri.org/IServices/UpdateNhanVienResponse")]
        void UpdateNhanVien(int manv, string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateNhanVien", ReplyAction="http://tempuri.org/IServices/UpdateNhanVienResponse")]
        System.Threading.Tasks.Task UpdateNhanVienAsync(int manv, string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelNhanVien", ReplyAction="http://tempuri.org/IServices/DelNhanVienResponse")]
        void DelNhanVien(int manv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelNhanVien", ReplyAction="http://tempuri.org/IServices/DelNhanVienResponse")]
        System.Threading.Tasks.Task DelNhanVienAsync(int manv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SearchNhanVien", ReplyAction="http://tempuri.org/IServices/SearchNhanVienResponse")]
        System.Data.DataTable SearchNhanVien(string tennv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SearchNhanVien", ReplyAction="http://tempuri.org/IServices/SearchNhanVienResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchNhanVienAsync(string tennv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showComboxNhanVien", ReplyAction="http://tempuri.org/IServices/showComboxNhanVienResponse")]
        System.Data.DataTable showComboxNhanVien();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showComboxNhanVien", ReplyAction="http://tempuri.org/IServices/showComboxNhanVienResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showComboxNhanVienAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertKhachHang", ReplyAction="http://tempuri.org/IServices/InsertKhachHangResponse")]
        void InsertKhachHang(string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertKhachHang", ReplyAction="http://tempuri.org/IServices/InsertKhachHangResponse")]
        System.Threading.Tasks.Task InsertKhachHangAsync(string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVKhachHang", ReplyAction="http://tempuri.org/IServices/showGVKhachHangResponse")]
        System.Data.DataTable showGVKhachHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVKhachHang", ReplyAction="http://tempuri.org/IServices/showGVKhachHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showGVKhachHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateKhachHang", ReplyAction="http://tempuri.org/IServices/UpdateKhachHangResponse")]
        void UpdateKhachHang(int makh, string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateKhachHang", ReplyAction="http://tempuri.org/IServices/UpdateKhachHangResponse")]
        System.Threading.Tasks.Task UpdateKhachHangAsync(int makh, string tenkh, string diachi, string dienthoai);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelKhachHang", ReplyAction="http://tempuri.org/IServices/DelKhachHangResponse")]
        void DelKhachHang(int makh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelKhachHang", ReplyAction="http://tempuri.org/IServices/DelKhachHangResponse")]
        System.Threading.Tasks.Task DelKhachHangAsync(int makh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SearchKhachHang", ReplyAction="http://tempuri.org/IServices/SearchKhachHangResponse")]
        System.Data.DataTable SearchKhachHang(string tenkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/SearchKhachHang", ReplyAction="http://tempuri.org/IServices/SearchKhachHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> SearchKhachHangAsync(string tenkh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showComboxKhachHang", ReplyAction="http://tempuri.org/IServices/showComboxKhachHangResponse")]
        System.Data.DataTable showComboxKhachHang();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showComboxKhachHang", ReplyAction="http://tempuri.org/IServices/showComboxKhachHangResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showComboxKhachHangAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertHoaDon", ReplyAction="http://tempuri.org/IServices/InsertHoaDonResponse")]
        void InsertHoaDon(int manv, int makh, System.DateTime ngayban, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertHoaDon", ReplyAction="http://tempuri.org/IServices/InsertHoaDonResponse")]
        System.Threading.Tasks.Task InsertHoaDonAsync(int manv, int makh, System.DateTime ngayban, float tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVHoaDon", ReplyAction="http://tempuri.org/IServices/showGVHoaDonResponse")]
        System.Data.DataTable showGVHoaDon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVHoaDon", ReplyAction="http://tempuri.org/IServices/showGVHoaDonResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showGVHoaDonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVHoaDonChiTiet", ReplyAction="http://tempuri.org/IServices/showGVHoaDonChiTietResponse")]
        System.Data.DataTable showGVHoaDonChiTiet(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/showGVHoaDonChiTiet", ReplyAction="http://tempuri.org/IServices/showGVHoaDonChiTietResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> showGVHoaDonChiTietAsync(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getGiaTien", ReplyAction="http://tempuri.org/IServices/getGiaTienResponse")]
        string getGiaTien(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getGiaTien", ReplyAction="http://tempuri.org/IServices/getGiaTienResponse")]
        System.Threading.Tasks.Task<string> getGiaTienAsync(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getSoLuong", ReplyAction="http://tempuri.org/IServices/getSoLuongResponse")]
        string getSoLuong(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getSoLuong", ReplyAction="http://tempuri.org/IServices/getSoLuongResponse")]
        System.Threading.Tasks.Task<string> getSoLuongAsync(int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getTongTien", ReplyAction="http://tempuri.org/IServices/getTongTienResponse")]
        string getTongTien(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getTongTien", ReplyAction="http://tempuri.org/IServices/getTongTienResponse")]
        System.Threading.Tasks.Task<string> getTongTienAsync(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getThongTinHD", ReplyAction="http://tempuri.org/IServices/getThongTinHDResponse")]
        System.Data.DataTable getThongTinHD(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getThongTinHD", ReplyAction="http://tempuri.org/IServices/getThongTinHDResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getThongTinHDAsync(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getThongTinSP", ReplyAction="http://tempuri.org/IServices/getThongTinSPResponse")]
        System.Data.DataTable getThongTinSP(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/getThongTinSP", ReplyAction="http://tempuri.org/IServices/getThongTinSPResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> getThongTinSPAsync(int mahd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/checkSanPham", ReplyAction="http://tempuri.org/IServices/checkSanPhamResponse")]
        bool checkSanPham(int mahd, int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/checkSanPham", ReplyAction="http://tempuri.org/IServices/checkSanPhamResponse")]
        System.Threading.Tasks.Task<bool> checkSanPhamAsync(int mahd, int masp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertChiTietHoaDon", ReplyAction="http://tempuri.org/IServices/InsertChiTietHoaDonResponse")]
        void InsertChiTietHoaDon(int mahd, int masp, int sl, float giaban, float thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/InsertChiTietHoaDon", ReplyAction="http://tempuri.org/IServices/InsertChiTietHoaDonResponse")]
        System.Threading.Tasks.Task InsertChiTietHoaDonAsync(int mahd, int masp, int sl, float giaban, float thanhtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateSoLuong", ReplyAction="http://tempuri.org/IServices/UpdateSoLuongResponse")]
        void UpdateSoLuong(int masp, double sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateSoLuong", ReplyAction="http://tempuri.org/IServices/UpdateSoLuongResponse")]
        System.Threading.Tasks.Task UpdateSoLuongAsync(int masp, double sl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateTongTien", ReplyAction="http://tempuri.org/IServices/UpdateTongTienResponse")]
        void UpdateTongTien(int mahd, double tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/UpdateTongTien", ReplyAction="http://tempuri.org/IServices/UpdateTongTienResponse")]
        System.Threading.Tasks.Task UpdateTongTienAsync(int mahd, double tongtien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelOne_ChiTietHoaDon", ReplyAction="http://tempuri.org/IServices/DelOne_ChiTietHoaDonResponse")]
        void DelOne_ChiTietHoaDon(int macthd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/DelOne_ChiTietHoaDon", ReplyAction="http://tempuri.org/IServices/DelOne_ChiTietHoaDonResponse")]
        System.Threading.Tasks.Task DelOne_ChiTietHoaDonAsync(int macthd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicesChannel : QL_TIEMBANH.Services.IServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicesClient : System.ServiceModel.ClientBase<QL_TIEMBANH.Services.IServices>, QL_TIEMBANH.Services.IServices {
        
        public ServicesClient() {
        }
        
        public ServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertSanPham(string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu) {
            base.Channel.InsertSanPham(tensp, soluong, giaban, ngaynhap, anh, ghichu);
        }
        
        public System.Threading.Tasks.Task InsertSanPhamAsync(string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu) {
            return base.Channel.InsertSanPhamAsync(tensp, soluong, giaban, ngaynhap, anh, ghichu);
        }
        
        public System.Data.DataTable showGVSanPham() {
            return base.Channel.showGVSanPham();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showGVSanPhamAsync() {
            return base.Channel.showGVSanPhamAsync();
        }
        
        public void UpdateSanPham(int masp, string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu) {
            base.Channel.UpdateSanPham(masp, tensp, soluong, giaban, ngaynhap, anh, ghichu);
        }
        
        public System.Threading.Tasks.Task UpdateSanPhamAsync(int masp, string tensp, int soluong, float giaban, System.DateTime ngaynhap, string anh, string ghichu) {
            return base.Channel.UpdateSanPhamAsync(masp, tensp, soluong, giaban, ngaynhap, anh, ghichu);
        }
        
        public void DelSanPham(int masp) {
            base.Channel.DelSanPham(masp);
        }
        
        public System.Threading.Tasks.Task DelSanPhamAsync(int masp) {
            return base.Channel.DelSanPhamAsync(masp);
        }
        
        public System.Data.DataTable SearchSanPham(string tensp) {
            return base.Channel.SearchSanPham(tensp);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchSanPhamAsync(string tensp) {
            return base.Channel.SearchSanPhamAsync(tensp);
        }
        
        public System.Data.DataTable showComboxSanPham() {
            return base.Channel.showComboxSanPham();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showComboxSanPhamAsync() {
            return base.Channel.showComboxSanPhamAsync();
        }
        
        public void InsertNhanVien(string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi) {
            base.Channel.InsertNhanVien(tennv, gioitinh, dienthoai, ngaysinh, diachi);
        }
        
        public System.Threading.Tasks.Task InsertNhanVienAsync(string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi) {
            return base.Channel.InsertNhanVienAsync(tennv, gioitinh, dienthoai, ngaysinh, diachi);
        }
        
        public System.Data.DataTable showGVNhanVien() {
            return base.Channel.showGVNhanVien();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showGVNhanVienAsync() {
            return base.Channel.showGVNhanVienAsync();
        }
        
        public void UpdateNhanVien(int manv, string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi) {
            base.Channel.UpdateNhanVien(manv, tennv, gioitinh, dienthoai, ngaysinh, diachi);
        }
        
        public System.Threading.Tasks.Task UpdateNhanVienAsync(int manv, string tennv, string gioitinh, string dienthoai, System.DateTime ngaysinh, string diachi) {
            return base.Channel.UpdateNhanVienAsync(manv, tennv, gioitinh, dienthoai, ngaysinh, diachi);
        }
        
        public void DelNhanVien(int manv) {
            base.Channel.DelNhanVien(manv);
        }
        
        public System.Threading.Tasks.Task DelNhanVienAsync(int manv) {
            return base.Channel.DelNhanVienAsync(manv);
        }
        
        public System.Data.DataTable SearchNhanVien(string tennv) {
            return base.Channel.SearchNhanVien(tennv);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchNhanVienAsync(string tennv) {
            return base.Channel.SearchNhanVienAsync(tennv);
        }
        
        public System.Data.DataTable showComboxNhanVien() {
            return base.Channel.showComboxNhanVien();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showComboxNhanVienAsync() {
            return base.Channel.showComboxNhanVienAsync();
        }
        
        public void InsertKhachHang(string tenkh, string diachi, string dienthoai) {
            base.Channel.InsertKhachHang(tenkh, diachi, dienthoai);
        }
        
        public System.Threading.Tasks.Task InsertKhachHangAsync(string tenkh, string diachi, string dienthoai) {
            return base.Channel.InsertKhachHangAsync(tenkh, diachi, dienthoai);
        }
        
        public System.Data.DataTable showGVKhachHang() {
            return base.Channel.showGVKhachHang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showGVKhachHangAsync() {
            return base.Channel.showGVKhachHangAsync();
        }
        
        public void UpdateKhachHang(int makh, string tenkh, string diachi, string dienthoai) {
            base.Channel.UpdateKhachHang(makh, tenkh, diachi, dienthoai);
        }
        
        public System.Threading.Tasks.Task UpdateKhachHangAsync(int makh, string tenkh, string diachi, string dienthoai) {
            return base.Channel.UpdateKhachHangAsync(makh, tenkh, diachi, dienthoai);
        }
        
        public void DelKhachHang(int makh) {
            base.Channel.DelKhachHang(makh);
        }
        
        public System.Threading.Tasks.Task DelKhachHangAsync(int makh) {
            return base.Channel.DelKhachHangAsync(makh);
        }
        
        public System.Data.DataTable SearchKhachHang(string tenkh) {
            return base.Channel.SearchKhachHang(tenkh);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SearchKhachHangAsync(string tenkh) {
            return base.Channel.SearchKhachHangAsync(tenkh);
        }
        
        public System.Data.DataTable showComboxKhachHang() {
            return base.Channel.showComboxKhachHang();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showComboxKhachHangAsync() {
            return base.Channel.showComboxKhachHangAsync();
        }
        
        public void InsertHoaDon(int manv, int makh, System.DateTime ngayban, float tongtien) {
            base.Channel.InsertHoaDon(manv, makh, ngayban, tongtien);
        }
        
        public System.Threading.Tasks.Task InsertHoaDonAsync(int manv, int makh, System.DateTime ngayban, float tongtien) {
            return base.Channel.InsertHoaDonAsync(manv, makh, ngayban, tongtien);
        }
        
        public System.Data.DataTable showGVHoaDon() {
            return base.Channel.showGVHoaDon();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showGVHoaDonAsync() {
            return base.Channel.showGVHoaDonAsync();
        }
        
        public System.Data.DataTable showGVHoaDonChiTiet(int mahd) {
            return base.Channel.showGVHoaDonChiTiet(mahd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> showGVHoaDonChiTietAsync(int mahd) {
            return base.Channel.showGVHoaDonChiTietAsync(mahd);
        }
        
        public string getGiaTien(int masp) {
            return base.Channel.getGiaTien(masp);
        }
        
        public System.Threading.Tasks.Task<string> getGiaTienAsync(int masp) {
            return base.Channel.getGiaTienAsync(masp);
        }
        
        public string getSoLuong(int masp) {
            return base.Channel.getSoLuong(masp);
        }
        
        public System.Threading.Tasks.Task<string> getSoLuongAsync(int masp) {
            return base.Channel.getSoLuongAsync(masp);
        }
        
        public string getTongTien(int mahd) {
            return base.Channel.getTongTien(mahd);
        }
        
        public System.Threading.Tasks.Task<string> getTongTienAsync(int mahd) {
            return base.Channel.getTongTienAsync(mahd);
        }
        
        public System.Data.DataTable getThongTinHD(int mahd) {
            return base.Channel.getThongTinHD(mahd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getThongTinHDAsync(int mahd) {
            return base.Channel.getThongTinHDAsync(mahd);
        }
        
        public System.Data.DataTable getThongTinSP(int mahd) {
            return base.Channel.getThongTinSP(mahd);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getThongTinSPAsync(int mahd) {
            return base.Channel.getThongTinSPAsync(mahd);
        }
        
        public bool checkSanPham(int mahd, int masp) {
            return base.Channel.checkSanPham(mahd, masp);
        }
        
        public System.Threading.Tasks.Task<bool> checkSanPhamAsync(int mahd, int masp) {
            return base.Channel.checkSanPhamAsync(mahd, masp);
        }
        
        public void InsertChiTietHoaDon(int mahd, int masp, int sl, float giaban, float thanhtien) {
            base.Channel.InsertChiTietHoaDon(mahd, masp, sl, giaban, thanhtien);
        }
        
        public System.Threading.Tasks.Task InsertChiTietHoaDonAsync(int mahd, int masp, int sl, float giaban, float thanhtien) {
            return base.Channel.InsertChiTietHoaDonAsync(mahd, masp, sl, giaban, thanhtien);
        }
        
        public void UpdateSoLuong(int masp, double sl) {
            base.Channel.UpdateSoLuong(masp, sl);
        }
        
        public System.Threading.Tasks.Task UpdateSoLuongAsync(int masp, double sl) {
            return base.Channel.UpdateSoLuongAsync(masp, sl);
        }
        
        public void UpdateTongTien(int mahd, double tongtien) {
            base.Channel.UpdateTongTien(mahd, tongtien);
        }
        
        public System.Threading.Tasks.Task UpdateTongTienAsync(int mahd, double tongtien) {
            return base.Channel.UpdateTongTienAsync(mahd, tongtien);
        }
        
        public void DelOne_ChiTietHoaDon(int macthd) {
            base.Channel.DelOne_ChiTietHoaDon(macthd);
        }
        
        public System.Threading.Tasks.Task DelOne_ChiTietHoaDonAsync(int macthd) {
            return base.Channel.DelOne_ChiTietHoaDonAsync(macthd);
        }
    }
}
